Fix issue #129 by rewriting the ARC handler yara rule.
IoT-Inspector/unblob pull request #130
Opened 2021-12-15 17:49 UTC by QKaiser

See #129

2021-12-17 10:47 UTC, QKaiser commented
I added two enhancements to ARC handler that will help with #129. Moved the size to an unsigned integer (should always be positive), and added a name validation function that verify if the file name is unicode encoded.

2022-01-04 09:26 UTC, vlaci requested changes

2022-01-04 09:26 UTC, vlaci commented on unblob/handlers/archive/arc.py
> +            snull(name.decode("utf-8"))
We first want to strip nulls, _then_ convert to string:
```suggestion
            snull(name).decode("utf-8")
```
This'll fix pyright and the test failure too

2022-01-04 12:33 UTC, vlaci commented
Hm, a file doesn't get extracted now :(

2022-01-04 12:47 UTC, vlaci commented
From the docstring of the yara rule:

>             Then a null-byte or unitialized-byte terminated filename string of 13 bytes, the
>             uninitialized byte is always set between 0xf0 and 0xff.

This matches with the output of the test:

> struct heads:
> - archive_marker: 0x1a
> - header_type: 0x2
> - name: b'apple.txt\x00\x00\x00\xfd'
> - size: 0x6
> - date: 0x5379
> - time: 0x6cef
> - crc: 0x3038
> - length: 0x6

This will trip on the `valid_name` check.

2022-01-05 13:47 UTC, QKaiser commented
Fixed `valid_name` by moving to this:

```python
# we don't care about the terminating byte (null or unitialized)
snull(name[:-1]).decode("utf-8")
```

2022-01-05 16:54 UTC, vlaci commented
Yaay, null bytes are valid unicode code points :D

2022-01-05 16:54 UTC, vlaci approved these changes

2022-01-05 17:04 UTC, merged