Extractor version doc
IoT-Inspector/unblob pull request #251
Opened 2022-02-14 13:56 UTC by kukovecz

Documenting extractors

2022-02-14 16:06 UTC, QKaiser requested changes
I'd suggest a table listing all the extractors currently in use with the version we recommend to use for each of them. This way we can point to it if we receive complaints from users who use old versions of 7z :)

This table should also point out whether it is automatically installed as part of Python dependency management (e.g. ubireader, jefferson) or needs to be installed manually.

2022-02-14 16:25 UTC, kukovecz commented on README.md
> +Unblob relies on various tools for extracting the contents of a blob. These extractors are either developed or externally using 3rd party tools, or internally (`unblob/extractors` directory). \
God, I was phrasing this for too much time and still managed to write this abomination. Thank you for fixing it up!

2022-02-14 16:27 UTC, kukovecz commented on README.md
> +* Check the `Dockerfile` how different extractors are installed (keeping mind of the extractor versions).
Great idea!

2022-02-15 10:28 UTC, kukovecz commented
> I'd suggest a table listing all the extractors currently in use with the version we recommend to use for each of them. This way we can point to it if we receive complaints from users who use old versions of 7z :)
> 
> This table should also point out whether it is automatically installed as part of Python dependency management (e.g. ubireader, jefferson) or needs to be installed manually.


I was lazy enough not to put a table like this consciously :sweat_smile: 
I just don't want the burden for the development by continuously updating the README, or make it possible to be outdated. But yeah, putting those versions explicitly here would maybe help the user more. 

Let's have a small brainstorm with the others what to do with this.

2022-02-16 18:06 UTC, vlaci commented
I'd put in the versions from the Ubuntu image we are currently using for tests (plus the 7z we are downloading). If we are to update the image, we need to update the docs as well but I don't think that it will be that frequent of an occasion.

2022-02-17 10:04 UTC, QKaiser approved these changes

2022-02-17 12:19 UTC, merged